In [200]:
import pandas as pd

In [201]:
# Loading guest data from the restaurant
guest_df = pd.read_csv("../data/WEEVA_GUESTS.csv")
guest_df.head(5)
# guest_df.shape

        DATE GUESTS
0  11/1/2018      0
1  11/2/2018      0
2  11/3/2018      0
3  11/4/2018      0
4  11/5/2018    108

In [202]:
# Loading weather data by time frame
weather_nov_2018_may_2021_df       = pd.read_csv("../data/Groningen 2018-11-01 to 2021-05-31.csv")
weather_june_2021_december_2023_df = pd.read_csv("../data/Groningen 2021-06-01 to 2023-12-31.csv")
weather_jan_2024_april_2025_df     = pd.read_csv("../data/Groningen 2024-01-01 to 2025-04-28.csv")

# Combining the weather datasets into one dataframe
weather_df = pd.concat([weather_nov_2018_may_2021_df, 
                        weather_june_2021_december_2023_df, 
                        weather_jan_2024_april_2025_df], 
                        ignore_index=True)

weather_df.head()
weather_df.shape

(2371, 33)

In [203]:
# Loading data on holidays and calendar dates
school_holidays_df           = pd.read_csv("../data/groningen_school_holidays_boolean.csv")
public_holidays_groningen_df = pd.read_csv("../data/public_holidays_2018_2025.csv")
public_holidays_germany_df   = pd.read_csv("../data/public_holidays_germany_2018_2025.csv")
calendar_df                  = pd.read_csv("../data/dates_with_weekdays.csv")

In [204]:
school_holidays_df.tail()
school_holidays_df.shape
school_holidays_df.dtypes

Date         object
IsHoliday    object
dtype: object

In [205]:
school_holidays_df["Date"] = pd.to_datetime(school_holidays_df["Date"])

start_date = '2018-11-01'
end_date = '2025-04-28'

# Filter to keep only dates within the desired range
school_holidays_df = school_holidays_df[
    (school_holidays_df['Date'] >= start_date) &
    (school_holidays_df['Date'] <= end_date)
]

# Remove duplicate dates, keeping the last occurrence
school_holidays_df = school_holidays_df.drop_duplicates(subset='Date', keep='last')

school_holidays_bool_df = pd.DataFrame(school_holidays_df)
# Convert 'Yes'/'No' to True/False in a specific column (e.g., 'IsHoliday')
school_holidays_bool_df['IsHoliday'] = school_holidays_bool_df['IsHoliday'].map({"Yes": True, "No": False})

school_holidays_bool_df.shape

/var/folders/bb/42kvx8fd08sf52k4xhjq2lth0000gn/T/ipykernel_85064/819521641.py:1: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  school_holidays_df["Date"] = pd.to_datetime(school_holidays_df["Date"])

(2371, 2)

In [206]:
public_holidays_groningen_df.head()
# public_holidays_groningen_df.shape

         Date                        Holiday
0  01.01.2018                 New Year's Day
1  02.04.2018                  Easter Monday
2  27.04.2018  Koningsdag (National Holiday)
3  10.05.2018                  Ascension Day
4  21.05.2018                    Whit Monday

In [207]:
# Setting the date column to the right data type
public_holidays_groningen_df["Date"] = pd.to_datetime(public_holidays_groningen_df["Date"], format='%d.%m.%Y')

# Defining a range of dates for the full holiday dataframe
date_range = pd.date_range(start='2018-11-01', end='2025-04-28', freq='D')

# Create a new DataFrame with that full date range
full_date_range_df = pd.DataFrame({'Date': date_range, 'Holiday': None})

# Assign the holiday to the corresponding dates
for index, row in public_holidays_groningen_df.iterrows():
    holiday_date = row['Date']
    holiday_name = row['Holiday']
    
    # Find the corresponding date in full_dates_df and update the Holiday column
    full_date_range_df.loc[full_date_range_df['Date'] == holiday_date, 'Holiday'] = holiday_name

full_date_range_df.head()
(full_date_range_df['Holiday'] != "None").sum()

2371

In [208]:
public_holidays_germany_df.head()
public_holidays_germany_df.shape

(72, 2)

In [209]:
calendar_df.head()
calendar_df.shape

(2371, 3)

In [210]:
# Loading data on number of items ordered in the restaurant
course_data_2018_2022_df = pd.read_csv("../data/Weeva_data_2018-2022.csv")
course_data_2023_2025_df = pd.read_csv("../data/Weeva_Data_2023-x.csv")

course_data_df = pd.concat([course_data_2018_2022_df, 
                            course_data_2023_2025_df], 
                            ignore_index=True)

course_data_df.head()
course_data_df.shape

(201293, 3)